name: Release

on:
  push:
    tags:
      - '*'  # Trigger on any new tag
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
      - name: Create releases
        run: |
          gh release create ${{ github.ref_name }} -R ${{ github.repository }}
          zip -r "$file_name" ${{ github.event.repository.name }} -x "*.git*"
          file_name="${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          gh release upload ${{ github.ref_name }} "$file_name" -R ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
